### ISSUE TITLE
Get-reguninstallkey/ps1 function

### ISSUE THREAD

**Issue by Gumbyohson** [djust270/Intune-Scripts#2]
Appreciated the regkey lookup you made on your blog. If we add this little bit at the bottom it'll ask for an app name and provide the output at the same time instead of having to register it again or manually call it at a later date.
```
$app = Read-Host -Prompt 'Input App search name'
Get-RegUninstallKey -displayname $app | select *uninstall*
```

**Comment by djust270** [comment]
Ah you are referring to the article deploying software with WinGet. Ill add this as an example in that article. Thanks!
