### ISSUE TITLE
Install-WingetTools.ps1 not creating module folder

### ISSUE THREAD

**Issue by Gumbyohson** [djust270/Intune-Scripts#3]
"$WebClient.DownloadFile($GithubURL, "$Env:TEMP\WingetTools.zip")" on line 56 appears to not function.
Replacing with:
$downloadfile = "$Env:TEMP\WingetTools.zip"
$WebClient.DownloadFile($GithubURL, $downloadfile) works correctly. Not sure of the exact reason.

**Comment by djust270** [comment]
I wasn't able to reproduce the issue, but I went ahead and updated the script and added a variable for the file. Also, I updated the GitHub URL replacing my fork of the module with the main repository for the module.
